### ISSUE TITLE
Black Layer Display

### ISSUE THREAD

**Issue by Jaydip2711** [malcommac/UIWindowTransitions#11]
When we are changing root view controller at a time some unknown black layer display for friction of second. can anyone have solution for that.

help are appreciate

**Comment by mkll** [comment]
@Jaydip2711 Just set `background` parameter, like below:

```
var options = UIWindow.TransitionOptions()
options.background = .solidColor(.white)
```

Or you may use your custom `UIView`:
```
options.background = .customView(UIView())
```

**Comment by boyuanx** [comment]
> @Jaydip2711 Just set `background` parameter, like below:
> 
> ```
> var options = UIWindow.TransitionOptions()
> options.background = .solidColor(.white)
> ```
> 
> Or you may use your custom `UIView`:
> 
> ```
> options.background = .customView(UIView())
> ```

That doesn't seem to have any effect... Hmm.

**Comment by Jaydip2711** [comment]
Thanks for helpiing

**Comment by mkll** [comment]
I always load first a UIViewController that mimics LaunchScreen, that's the reason why I didn't face the problem with background you wrote about. Glad that it helped.
