### ISSUE TITLE
Suggestion to discourage re-setting the rootViewController of the UIWindow

### ISSUE THREAD

**Issue by JaviSoto** [malcommac/UIWindowTransitions#7]
Hi!

This project showed up in this weekly email I get from Github with interesting repos. Really cool stuff :) Animating this is something I have struggled with, so this is really useful.

I just wanted to share something that I learned working on the Twitch app. We were resetting the `rootViewController` whenever the user would log in/out. But then we realized that UIKit can actually leak entire view controllers (if I remember correctly, if there's any view controller presented modally on top of the rootViewController, and then you update it on the `UIWindow`).

Our solution was fairly straight-forward: we create a `class RootViewController: UIViewController` that's ALWAYS the rootViewController, but it's a container controller, and allows you to swap the inner view controller. This is also easy to animate.

Anyway, hope that this is useful :) Sorry I don't have more details (like a radar, or specifics about how the issue manifested), it was months ago and I didn't work on it myself.

**Comment by sushant40** [comment]
I noticed this memory leak with uikit myself while using this library. Do you have sample code showing how to implement the RootViewController that you mentioned - @JaviSoto ?

**Comment by JaviSoto** [comment]
Sorry, I don't have something I can share at the moment.

**Comment by boyuanx** [comment]
Does it still leak if all other view controllers are dismissed/popped?

**Comment by sushant40** [comment]
I spent some time looking into this issue and after finding a solution I created a POD that works similar to this library (in fact it uses code from this library). You can use...

https://github.com/voltbank/ReplaceRootViewController

**Comment by malcommac** [comment]
Thanks for your contribution, I've ported your changes to the project, updated the readme with your contribution and updated for Swift 5.
